name: peludos_pet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  flutter_meedu: ^8.3.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  firebase_app_check: ^0.2.2+5
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/