// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHV9Vpvm8JzIZMniX_-OXERLMR_TBwj6A',
    appId: '1:343584925408:web:02a3ccfbd50e094eb2d285',
    messagingSenderId: '343584925408',
    projectId: 'peludospet-285e2',
    authDomain: 'peludospet-285e2.firebaseapp.com',
    storageBucket: 'peludospet-285e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvRLVQknJiaNKr5-0z9wBi8WmCxWBQYRM',
    appId: '1:343584925408:android:6f55d64592d0d275b2d285',
    messagingSenderId: '343584925408',
    projectId: 'peludospet-285e2',
    storageBucket: 'peludospet-285e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTaM3L28A7HPYUXQnpZIoikWCwhTtDvo',
    appId: '1:343584925408:ios:e33dfc6678805120b2d285',
    messagingSenderId: '343584925408',
    projectId: 'peludospet-285e2',
    storageBucket: 'peludospet-285e2.appspot.com',
    iosBundleId: 'com.example.peludosPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoTaM3L28A7HPYUXQnpZIoikWCwhTtDvo',
    appId: '1:343584925408:ios:e33dfc6678805120b2d285',
    messagingSenderId: '343584925408',
    projectId: 'peludospet-285e2',
    storageBucket: 'peludospet-285e2.appspot.com',
    iosBundleId: 'com.example.peludosPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHV9Vpvm8JzIZMniX_-OXERLMR_TBwj6A',
    appId: '1:343584925408:web:1915547cebcadd9cb2d285',
    messagingSenderId: '343584925408',
    projectId: 'peludospet-285e2',
    authDomain: 'peludospet-285e2.firebaseapp.com',
    storageBucket: 'peludospet-285e2.appspot.com',
  );

}